### ISSUE TITLE
migrate to the new version of velero

### ISSUE THREAD

**Issue by georgettica** [openshift/managed-velero-operator#109]
after some pushing and shoving in the velero repo, the binary can be installed without dependencies with old versions of k8s (allowing us to migrate to higher k8s versions)

https://github.com/vmware-tanzu/velero/issues/2966

I can also card it up if needed :)

**Comment by cblecker** [comment]
We are on the latest released version already, and track new releases when they come out. No action required.

/close

**Comment by georgettica** [comment]
sorry, thanks :)
