### ISSUE TITLE
ClusterServiceVersion not found

### ISSUE THREAD

**Issue by flickerfly** [openshift/managed-velero-operator#63]
I'd like to look into including this in an internal Operator Catalog, but can't find any CSVs available. I wonder if that is something you might be able to provide? Looks like this is an Operator SDK like operator so maybe that's pretty easy to run the operator bundle creation.

**Comment by cblecker** [comment]
Hi @flickerfly,
We don't really provide support for this operator outside if it's use in some of our managed environments. I would check out https://github.com/openshift/oadp-operator as it uses velero at it's core as well.

Thanks!

/remove-lifecycle frozen
/close
