### ISSUE TITLE
How to backup & restore to another cluster

### ISSUE THREAD

**Issue by kahootali** [openshift/managed-velero-operator#89]
I want to take backup from one cluster & restore to another cluster, but issue is when i run this in one cluster, it creates a new S3 bucket with limited permissions, and when I deploy velero operator on second cluster, it will create another S3 bucket and policies. So I am unable to take backup from one cluster and then restore it in other cluster

**Comment by cblecker** [comment]
@kahootali If you want to take a backup and restore it to another cluster, you may need to add the first cluster's BSL to the second cluster that you intend to restore on: https://velero.io/docs/v1.5/api-types/backupstoragelocation/

You may also want to look into the CAM tool: https://www.openshift.com/learn/topics/migration

**Comment by kahootali** [comment]
I did that, but issue is 2nd cluster wasn't able to access 1st cluster's S3 bucket and gave error of Access Denied

**Comment by kahootali** [comment]
@cblecker Any idea?
